feat: add conditional custom theme with persistence and defaults.json for default export list
hyphacoop/reader.distributed.press pull request #29
Opened 2024-09-20 19:14 UTC by akhileshthite

https://github.com/hyphacoop/reader.distributed.press/issues/28

![Screen Shot 2024-09-20 at 11 49 09 AM](https://github.com/user-attachments/assets/ac65a0ca-3131-4daa-aa07-716f3a22355b)

2024-09-20 22:10 UTC, akhileshthite commented on about.html
> +      <details>
![Screen Shot 2024-09-20 at 3 09 43 PM](https://github.com/user-attachments/assets/98d25239-3030-4e44-a935-69b5caedce21)

2024-09-20 22:10 UTC, akhileshthite commented on timeline.js
> +    this.loadingText.textContent = 'Loading...'
![Screen Shot 2024-09-20 at 3 05 28 PM](https://github.com/user-attachments/assets/24c4fc06-5fd2-4cf7-9cb0-27dcc8a88ab4)

2024-09-20 22:13 UTC, akhileshthite commented on defaults.js
> +    // Determine if the custom theme differs from the default light theme
The "custom" option will appear as a default option if the social reader default json list changes.

2024-09-30 01:33 UTC, akhileshthite commented on sidebar.html
> +<div id="release-version" class="release-version"></div>
![PHOTO-2024-09-29-18-31-54](https://github.com/user-attachments/assets/9213bbd8-b533-46df-8b22-778685a7b923)

2024-09-30 15:19 UTC, RangerMauve requested changes
THis looks great! just one comment about the version

2024-09-30 18:14 UTC, akhileshthite commented
> THis looks great! just one comment about the version

I don't see your review comment 🤔

2024-10-01 20:43 UTC, RangerMauve requested changes

2024-10-01 20:43 UTC, RangerMauve commented on sidebar.js
> +const defaultJsonUrl = './config/defaults.json'
Does this work on all pages? I think we need absolute URLs or to use `import.meta.url` to generate a URL relative to the sidebar file

2024-10-01 23:08 UTC, akhileshthite commented
I just tested everything. Before we merge, we need to fix one issue:

Previously, the "Load More" button would appear after following an actor, allowing me to view all their posts (main branch's timeline). However, I am now encountering an issue where the "Load More" button initially appears, but disappears from the timeline after following an actor. I am unable to navigate all the way to the oldest posts on other timelines because the "Load More" button only appears once, and doesn't reappear for subsequent loading like it used to.

2024-10-09 17:51 UTC, RangerMauve commented
Are you getting errors?

2024-10-12 04:46 UTC, akhileshthite commented
> Are you getting errors?

It's working now, can you test it?

2024-10-17 18:44 UTC, RangerMauve approved these changes
Looks good to me 👍👍👍👍

2024-10-17 18:45 UTC, merged